---
- project:
    templates:
      - publish-stx-docs
      - stx-release-notes-jobs
    check:
      jobs:
        - starlingx-common-tox-pep8
        - starlingx-common-tox-linters
        - stx-virt-pylint
    gate:
      jobs:
        - starlingx-common-tox-pep8
        - starlingx-common-tox-linters
        - stx-virt-pylint
    post:
      jobs:
        - stx-virt-upload-git-mirror

# This is the common base job definition for StarlingX flock services
- job:
    name: flock-devstack-virt-base
    parent: devstack
    description: |
      Base job for StarlingX Flock components DevStack tests
    nodeset: debian-bullseye
    roles:
      - zuul: openstack/devstack
    timeout: 9000
    required-projects:
      - name: openstack/devstack
      - name: openstack/keystone
      - name: openstack/requirements
    vars:
      devstack_services:
        ceilometer-acentral: false
        ceilometer-acompute: false
        ceilometer-alarm-evaluator: false
        ceilometer-alarm-notifier: false
        ceilometer-anotification: false
        ceilometer-api: false
        ceilometer-collector: false
        horizon: false
        # Swift services
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
        tempest: false
        # Database
        mysql: false
        postgresql: true
      devstack_localrc:
        # LIBS_FROM_GIT: keystone
        FORCE: yes

# A minimal base job that eliminates most OpenStack services
# Leave Celiometer, Horizon and Swift in the base since none
# of our jobs need them.
- job:
    name: flock-devstack-virt-base-min
    parent: flock-devstack-virt-base
    timeout: 7800
    vars:
      devstack_services:
        # Cinder services
        c-api: false
        c-bak: false
        c-sch: false
        c-vol: false
        cinder: false
        # Glance services
        g-api: false
        g-reg: false
        # Nova services
        n-api: false
        n-api-meta: false
        n-cauth: false
        n-cond: false
        n-cpu: false
        n-novnc: false
        n-obj: false
        n-sch: false
        placement-api: false
        # Neutron services
        q-agt: true
        q-dhcp: false
        q-l3: false
        q-meta: false
        q-metering: false
        q-svc: false

# An equivalent tox-based functional test job to flock-devstack-virt-base
- job:
    name: flock-devstack-virt-tox-base
    parent: devstack-tox-functional
    description: |
      Base job for StarlingX Flock components DevStack tests that use tox
    nodeset: debian-bullseye
    roles:
      - zuul: openstack/devstack
    timeout: 9000
    required-projects:
      - name: openstack/devstack
      - name: openstack/keystone
      - name: openstack/requirements
    vars:
      devstack_services:
        ceilometer-acentral: false
        ceilometer-acompute: false
        ceilometer-alarm-evaluator: false
        ceilometer-alarm-notifier: false
        ceilometer-anotification: false
        ceilometer-api: false
        ceilometer-collector: false
        horizon: false
        # Swift services
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
        tempest: false
        # Database
        mysql: false
        postgresql: true
      devstack_localrc:
        # LIBS_FROM_GIT: keystone
        FORCE: yes

# And the tox version of the base-min job
- job:
    name: flock-devstack-virt-tox-base-min
    parent: flock-devstack-virt-tox-base
    timeout: 7800
    vars:
      devstack_services:
        # Cinder services
        c-api: false
        c-bak: false
        c-sch: false
        c-vol: false
        cinder: false
        # Glance services
        g-api: false
        g-reg: false
        # Nova services
        n-api: false
        n-api-meta: false
        n-cauth: false
        n-cond: false
        n-cpu: false
        n-novnc: false
        n-obj: false
        n-sch: false
        placement-api: false
        # Neutron services
        q-agt: true
        q-dhcp: false
        q-l3: false
        q-meta: false
        q-metering: false
        q-svc: false

# Try this as a tox-based job with a minimal functional target in tox.ini
- job:
    name: stx-virt-pylint
    parent: tox
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
    vars:
      tox_envlist: pylint
      tox_extra_args: -c tox.ini

- job:
    name: stx-virt-upload-git-mirror
    parent: upload-git-mirror
    description: >
      Mirrors opendev.org/starlingx/virt to
      github.com/starlingx/virt
    vars:
      git_mirror_repository: starlingx/virt
    secrets:
      - name: git_mirror_credentials
        secret: stx-virt-github-secret3
        pass-to-parent: true

- secret:
    name: stx-virt-github-secret3
    data:
      user: git
      host: github.com
      # yamllint disable-line rule:line-length
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      ssh_key: !encrypted/pkcs1-oaep
        - rWw4uL5vF79qBjDVdAu5RyGdlXuozYnydisQS3E9qN636qbnkyYMOP3ewLyL2JKvCjkkz
          hj/z2015XSVCuF7dEYgAFSLq8a03HUIkzBrWZp7N0D1s+lZV0fl5kR0FUsTAC8p/QiC+r
          IbTEWf57qaBEzxWJzNOO9cgebdx+2PlB13MY1HGTg5j2JaxLIrXxeZdpiDMOVkffmHBF7
          jL38of5ZgUCdRT5kCXC+vcfvXsCAJE9xWJvs5EY9x9M7YovqneTSxf1ciirmQbOEYGJcU
          p6NWlkGSR7KFzOx1luc9waKMpkqpMAsmp7bqsXjXB218k3EHa1kt52ThJcMffjRlQQ6np
          2IAJLokAqQlExatRsmB8VTKLpe0r3vtP40WJNLH2JwMb03tKIHLmiFwvaz2jwK90/UaKD
          M+epyVo+IbVkhiItJUYwmuwCvoekMn98nz2GRwZPDpqmWvon1MN8Toca0PEARh8fJKfqk
          m5RNF6laJUHLsK254JsMdx/jpWNJ6lr+KpIax4QWzt9ImmNkhcqE8SCJDQVEnNVUH0SAI
          3f9+jtrYQcb29m4fkczVJ2QR1BP2bo9MVL/dxlqoCvdjgUELBjMNUQCt51xOQPZBpxLso
          CRecR8LmKbsmOtZd1SroHatj9eYUQRAhTxJyHX8HZT20F3Gswst6vtG1tssQVY=
        - Gb37SWjemSRHsIWcBVOPYmmugwuMkfwMStVdmp/PgVHBkdNZPMqrEY9tsk9GKy8hBC+Ik
          WaNrPzvaNKIduo8oWQtMGiSYcV9A0GYBF9HC6N3jEtbYBkd1HoeS0MtsbLTuDuepYdZHf
          4l7dTSHiTv3ZCwrRJVjm7gqh2ONnB0pRW1m1AvrjMFtuHRphXWT/bVe5PfkAxOU11Ff2J
          Nwc3xgNwvJWfcV4f+jpz9KUT1ItFBKI7R5g6GWQd+a7DtK0DUq5oJ46cWC+n9T/wsibsq
          3Rx6isNBJw6RaV0QSfHxvV6fYXdpY4XpAy1XGny09TJk7lI8ga9BRcl5z6kddwtbtBPpe
          F7oun7/8nJVW9Da3NYpmLBRx3EFCvaasA2UnZlUz4ccKnjNrNqon7KgqyOFtrq1zLpzyI
          g/A8hNywi9NPpq/7JkLdSSgc80kkp760HUXiYrJII0zW4OGGNd03mmU9l3xLkh2akgiky
          NJJ0iYXlZy/ga3oj9gjl1NeyzT8AWRsX/lCGFFDA7jsG4oUME7R2IM4/JtgPfvI7ZoIIW
          8K/HbXJ7i4yP4+hcegFviPBXsUuYj1LdahAPos/4amhsGJoT4nXVkoE8Ued/TL4V5afkf
          7jkath+PD/3K0PmdKIEle0RsbxsvVBJ8JSAX6q2OqUJRnpmsfRPBGpWLME78iY=
        - PlR6afEWehRRRQzo44z0QoisT/RIEpZhWatwaqP6guwD/RWRSvFYiVZKy2dgdRNzrC6kt
          bDvYjBYAkR6vg0DkySqronSvcDz1aYh5pn4rLOydPIYaRnLIdkzxnqWpCR9aQCG5I/IZ3
          KLy2ABST3c5LmDWsIdbBIQq2+Vbi36ifaZFkeNQQaTvoZvxPrWj/1wrRl0AW7cQc+Uuvu
          OSGapdwAzzPb/8TSBT+POexjkm4BFV9TMdASBqJ+9zYXzSXae3GQ4jcfcIbBDoVjicLGK
          mOvza6Z8zwe4+lIOMNu6iSj+tNVCdVUcxHeo7RKy/yntw4z3ePnvYCWRy1LHhfkpfdbRx
          UQUBTLRRyqH1CGoVacWXu6MNyYyIw3XSlfQN1yJ0X5cqfMrZiEkmvVZjujIIi2WkM0oOq
          m0tKrdsdknEFggkd4oUWaOiUdHxlmd6bOyI0YNJiyjKqkos2Cfdhp1WmeGeoUZG9lq7xG
          zl0bX0nC7pFwRIU7XJdA1HMZKAXSMPz52/yGxp8/EZWP9/71Z3JKBmYM6c2kf0zm3eb2y
          UQCjOWE6b4e6mqosmNR1QdVWt1qpzKYByUo+e9MPjXKKv//hydq0M0mYr7LcppbmmbduF
          Mc9g9PXAr5k4i84yKqlxHH848a0uGDKLTZzyXYfhlnzNO5usXI8EPHBTJmU8gU=
        - R2BDx1BytnUmkafyRqcKeQOV6mNL1oXXlBKO9qYrxyGb/myyjSD24plP2lq8W74dZAmyx
          jS4AVgfrWCHE8P7gXvDAqipZ1JjRER3JKN1Qeaiu9gj0BqEfB8LGuNJxDFW6u8p6SH018
          O/n3N3EKiKtb7ktMwFc9N63DjAhKFj79zTvVmqrp9sdpHR9iUV9BppMzTdy12K/JfPwrU
          YDXgkqYB1WSyKaWe5/KqsrkDbT0Q+R2UP5UPJLhsLzqNiGJAgC7B4/vD6qSoFF2ypTEkH
          dxfh614o98MiYDX4hAbW1EB+VQYsmdfnAiSeyoJl+waqWjZWRreCii6/74rHa+ZYY9jAF
          u/0dMPCE1xPA/pWtGJ4n/Y949/x4w13bAnLShA6T/saM2A2VpaF2rr7ArWJGMeCLQxw0Z
          u+N11bkkN73vGDU4QbLc/EXHCR4GTu0uhK6G2b/jNwGsedYkL+LAs+51DqyjS7q9IYhET
          Yj3vKPu7YxjGosv480vy2AQNeSpoDXFwmToYpyNpznpy0pjI/QvqxAu244n9Y3kFGoDaO
          ltCWTqHgk8ZkqtcYVsLwpVzVuGJCP6ADjewVzoBLtNIQr8DWLz3V9Up4+G8dqEnd5UDgd
          AxXJhO88cfcyTzx9yQNOuH75nvjEjx/Ivtf4hp2hcGeU3rk3KxDdUmd+3H73ao=
        - iVgWyBkNbZHT9HWHZIy4khCTOu5U2Oej8GdjOoyGkUfg6pgygpzABIJObtnHwnlGBIeLY
          ijaPwIiVrmR0J3iwt4p37GSeTtjn61Y/d8yICEBx4VqchDmejjsFbCJX8WUcSoTI3J/+0
          x4KDBtOhtMnKOko4WUdZg0OOx05J1haKuDpG0ht8kNGQX8SN+2y26bFfkAjbvwcYu/fsK
          1CCSxk64iO54eUvoS3Hve6Xe7S+0mctujgUlqxE9yXtFVnABzgnmdCb06vE8lEZurV4NX
          4gjm45uLfERX4STcuV+ZfU3GVfAvQKZuDV0ZcO3OiuzNoqbUAmBei1Rb7XjPSJ7a29pDr
          +YQEEL67J0lov2VNeZiU1Cze1MGajHdzIOzWXldXk+KfKPABbr/YE+ZD1GtVYnareuRIK
          3tpZ7AL6tGkMHBFlaHmBU4vF6Q5+xySvLx+R9SUZAoSdw1okpVceWyc4TUgsbyWgIoDm/
          Sv5bIb/4xBD4DYOefHvPMYFT8xsuKTXgfxOu1KJXRwvyJIVOEPNlyx683agSc/piBl+5C
          iTxotX8MWhCzMiaGGxLpYGnzTOqtwyrLmH/wLot7eSq9N2vM/GjVle7rDV1Smgzicu2+a
          UHnl7Q5xTzeOV8bvGCGr7H05kxR9AoPgE7q7TOjMq98VgfBn1rHI02o5wt+GXM=
        - zQMfImUrKlqMwOaWU686jt1Hu754gFXiSTw+udaphp5Hx+knC0MlJkhvZK/1BLKh8z4jM
          QqDAp9cs7UXNRnMCGyTfE5nvBhAPEI3SalS8yuHkEOTcPhxoelTLCkKNuRhI70EfvlNde
          vlMHFdsPCWM4/q6ZG/hVWGg/ks/Ht0Chc9o2QzArG3wdC4oSIVN/WhegkQ6hyBeqvXATN
          8SxHUAFNkDfHWwLWpH5iig25ycdeRtrsEHvSBc5ORVI9A6pGf99FkCVg1PpUH8l9/Xlv+
          +l19ADV/b65MM0Qhj5YPB6KVFZit9L4fPeOZTjAqdqEWl5+hYSx5rbBi+CPBU17aOsAnq
          5rc7t4zLo62hF3s0wThKNyTNp+YlEvjvUotPhUSWPskbZBWcCK6qBbssGeZ0mQNKUtCaw
          yv/3Aotd+w4GcXDy3UQbXxgddzqowjF7frDrE0KVhe7xOBy2Gp5Ny3NRgN7Rcr/zXwjs5
          rAGhfRc/DfKbaNi7WVl0+OXfqxItAOvVCEujXzbLGVclMiWcTfxwAQzH+LW5oXEX68pGJ
          Xavq3VLsca+zdwmJx+gajoU+LnMTMiy+jVZixnhp2DHRL20r6JZRElrN7KWbsA72TRyrZ
          QT3cCKDpbc6B1NM/CzL9RTBfvDdDzeq7lVZ/LvDJ0OKfVrsQ2ZXh8IW5YodhcA=
        - dTfchHYbPjq00jwaWIr245TbEn3PkNm5hwo4//zd0RwAjB6k1tDckWxB6js+DyP4pJmUv
          mjUek1UwQy2L1DefgJ/UJlfyFyz8Uc9ga9wH4XHaow3gdHtNM3SQahM5Z24DnqkstwDyh
          jsdr1I6Faa9y4Wx0jCfjossrPHzEfureBUrs0XpzzVQkujm7RWh2+85iJ0me0QFEw1seg
          ldX0jMykS7QYFq3XKL+ndgaoFZnI0GfPyBDte5naSfnydbDUEC4qFkUzskAPodBaVzpJs
          m+342Df/8qwkL1yqPYZ/M4YD9GaZu/WJYkH7zUlRzGYpfgEbEaesG645KjWEcmIlGv511
          u/Z7zPQN6X9VcG/MXE3ONdoNyzTtB643rCP/aA0qj+G0R9MqIGSYixGZ76BijCPKHLXf6
          lKZ0knlkHAjGs3mOSsR8L6BvySAfDdbv54HANFHjd5UCVfgTk2gRdK4sVgrFQgDX6U11y
          mAsJFarHTEEc7EDoRoD6/3PiwP0ljWnU4sEdvmN3FVrCAGBNQ9kUsPVpD7SejRdWzmPt1
          UIyh32LQgTe5G6mMg1fDr8LBneFDhT515sGWqbOWW0z2yAvZCKsPv/kOr5ywb+IDzIBr0
          IgadYkQDiQ+wyevl4l7U7JYJOqxhKTU5e76+j+S/ZJ/e91tMSwvYrsRmc8n/aI=
